export const RolePermissions: Record<string, string[]> = {
  admin: ["*"],
  hotel_manager: [
    "hotel:create",
    "hotel:read",
    "hotel:update",
    "hotel:delete",
    "room:create",
    "room:read",
    "room:update",
    "room:delete",
    "roomCategory:create",
    "roomCategory:read",
    "roomCategory:update",
    "roomCategory:delete",
    "category:read",
    "booking:read",
  ],
  customer: [
    "hotel:read",
    "room:read",
    "roomCategory:read",
    "category:read",
    "booking:create",
    "booking:read",
    "booking:confirm",
    "booking:cancel",
    "review:create",
    "review:read",
    "review:delete",
  ],
};
