{
 "title": "Dashboard-from-scratch",
 "tags": [
  "booking-platform",
  "microservices",
  "observability"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Request ID" }
  ]
 },
 "panels": [
  {
   "title": "AuthService Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"AuthService\"}",
     "legendFormat": "AuthService"
    }
   ]
  },
  {
   "title": "BookingService Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"BookingService\"}",
     "legendFormat": "BookingService"
    }
   ]
  },
  {
   "title": "HotelService Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"HotelService\"}",
     "legendFormat": "HotelService"
    }
   ]
  },
  {
   "title": "NotificationService Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"NotificationService\"}",
     "legendFormat": "NotificationService"
    }
   ]
  },
  {
   "title": "PaymentService Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"PaymentService\"}",
     "legendFormat": "PaymentService"
    }
   ]
  },
  {
   "title": "ReviewService Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ReviewService\"}",
     "legendFormat": "ReviewService"
    }
   ]
  },
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\".+\"} | route !~ \"/metrics|/health\""
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{route!=\"/metrics\",route!=\"/health\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Service - Error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"AuthService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"AuthService\"}[5m]))",
     "legendFormat": "AuthService"
    },
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"BookingService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"BookingService\"}[5m]))",
     "legendFormat": "BookingService"
    },
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"HotelService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"HotelService\"}[5m]))",
     "legendFormat": "HotelService"
    },
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"NotificationService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"NotificationService\"}[5m]))",
     "legendFormat": "NotificationService"
    },
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"PaymentService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"PaymentService\"}[5m]))",
     "legendFormat": "PaymentService"
    },
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"ReviewService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"ReviewService\"}[5m]))",
     "legendFormat": "ReviewService"
    }
   ]
  },
  {
   "title": "Gateway Error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{job=\"AuthService\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"AuthService\"}[5m]))",
     "legendFormat": "Gateway Error %"
    }
   ]
  },
  {
   "title": "Gateway P95 Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"AuthService\",route!=\"/metrics\",route!=\"/health\"}[5m])) by (le))",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Gateway Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"AuthService\",route!=\"/metrics\",route!=\"/health\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Service Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{route!=\"/metrics\",route!=\"/health\"}[5m])) by (job, status_code)",
     "legendFormat": "{{job}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=~\".+\"} | level=\"error\" | route !~ \"/metrics|/health\""
    }
   ]
  },
  {
   "title": "Top 10 Slowest Routes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.95, sum by(route, le)(rate(http_request_duration_seconds_bucket{route!=\"/metrics\",route!=\"/health\"}[5m]))))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Error Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status_code=~\"5..\",route!=\"/metrics\",route!=\"/health\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Search",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{job=~\".+\"} | requestId=~\"$Request ID\" | route !~ \"/metrics|/health\""
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{route!=\"/metrics\",route!=\"/health\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{route!=\"/metrics\",route!=\"/health\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}