export const BOOKING_CREATED_EVENT = "BOOKING_CREATED";
//  BOOKING_CONFIRMED_EVENT is never emitted (confirmation handled by payment-event-consumer)
// export const BOOKING_CONFIRMED_EVENT = "BOOKING_CONFIRMED";
export const BOOKING_CANCELLED_EVENT = "BOOKING_CANCELLED";
export const BOOKING_STAY_COMPLETED_EVENT = "BOOKING_STAY_COMPLETED";
