global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "AuthService"
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "HotelService"
    static_configs:
      - targets: ["host.docker.internal:3001"]

  - job_name: "BookingService"
    static_configs:
      - targets: ["host.docker.internal:3002"]

  - job_name: "ReviewService"
    static_configs:
      - targets: ["host.docker.internal:3003"]

  - job_name: "NotificationService"
    static_configs:
      - targets: ["host.docker.internal:3004"]
