global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "AuthService"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3000"]

  - job_name: "HotelService"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3001"]

  - job_name: "BookingService"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3002"]

  - job_name: "ReviewService"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3003"]

  - job_name: "NotificationService"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3004"]

  - job_name: "PaymentService"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:3005"]
