version: "3"

vars:
  DB_DSN: root:root@tcp(127.0.0.1:3306)/review_service

tasks:
  migrate-up:
    cmds:
      - goose -dir db/migrations mysql "{{.DB_DSN}}" up

  migrate-down:
    cmds:
      - goose -dir db/migrations mysql "{{.DB_DSN}}" down

  migrate-create:
    cmds:
      - goose -dir db/migrations create {{.CLI_ARGS | default "migration"}} sql

  seed-up:
    cmds:
      - goose -dir db/seeds mysql "{{.DB_DSN}}" up

  seed-down:
    cmds:
      - goose -dir db/seeds mysql "{{.DB_DSN}}" down

  seed-reset:
    cmds:
      - goose -dir db/seeds mysql "{{.DB_DSN}}" reset

# task migrate-up
# task migrate-down
# task seed-up
# task seed-down
# task seed-reset
