version: "3"

vars:
  DB_DSN: root:password@tcp(127.0.0.1:3306)/review_service

tasks:
  migrate-up:
    cmds:
      - goose -dir db/migrations mysql "{{.DB_DSN}}" up

  migrate-down:
    cmds:
      - goose -dir db/migrations mysql "{{.DB_DSN}}" down

  migrate-create:
    cmds:
      - goose -dir db/migrations create {{.CLI_ARGS | default "migration"}} sql

  seed-up:

  seed-reset:
    cmds:
      
# task migrate-up
# task migrate-down
